const plants = [
	{
		id: 0,
		name: 'Aglaonema "Moro Ninja"',
		category: 'aglaonema',
		price: 89.99,
		image: './assets/aglaonema_moro_ninja.jpg',
		description: [
			'stanowisko jasne, ale bez bezpośredniego nasłonecznienia',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'umiarkowana wilgotność podłoża',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 1,
		name: 'Aglaonema "Brightness Queen"',
		category: 'aglaonema',
		price: 85.99,
		image: './assets/aglaonema_brightness_queen.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'umiarkowana wilgotność podłoża',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 2,
		name: 'Aglaonema "Silverado"',
		category: 'aglaonema',
		price: 56.99,
		image: './assets/aglaonema_silverado.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 3,
		name: 'Aglaonema "Prestige"',
		category: 'aglaonema',
		price: 78.99,
		image: './assets/aglaonema_prestige.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 4,
		name: 'Aglaonema "Crete Flame"',
		category: 'aglaonema',
		price: 59.99,
		image: './assets/aglaonema_crete_flame.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'jako roślina tropikalna źle znosi suszę i lubi zraszanie liści',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 5,
		name: 'Aglaonema "Cinta"',
		category: 'aglaonema',
		price: 59.99,
		image: './assets/aglaonema_cinta.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'jako roślina tropikalna źle znosi suszę i lubi zraszanie liści',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 6,
		name: 'Aglaonema "Red Lipstick"',
		category: 'aglaonema',
		price: 99.99,
		image: './assets/aglaonema_red_lipstick.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 7,
		name: 'Aglaonema "Chamaeleon Bandit"',
		category: 'aglaonema',
		price: 119.99,
		image: './assets/aglaonema_chamaeleon_bandit.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 8,
		name: 'Ceropegia "Woodii"',
		category: 'ceropegia',
		price: 39.99,
		image: './assets/ceropegia_woodii.jpg',
		description: [
			'stanowisko jasne',
			'brak odpowiedniej ilości światła powoduje, że zwiększa się odległość między liśćmi',
			'lubi miejsca ciepłe o temperaturze 20 – 22°C',
			'podłoże być przepuszczalne i dobrze zdrenowane',
		],
	},
	{
		id: 9,
		name: 'Ceropegia "Woodii Variegata"',
		category: 'ceropegia',
		price: 44.99,
		image: './assets/ceropegia_woodii_variegata.jpg',
		description: [
			'stanowisko jasne',
			'brak odpowiedniej ilości światła powoduje, że zwiększa się odległość między liśćmi',
			'lubi miejsca ciepłe o temperaturze 20 – 22°C',
			'podłoże być przepuszczalne i dobrze zdrenowane',
		],
	},
]
