const plants = [
	{
		id: 0,
		name: 'Aglaonema "Moro Ninja"',
		category: 'aglaonema',
		price: 90.0,
		image: './assets/aglaonema_moro_ninja.jpg',
		description: [
			'stanowisko jasne, ale bez bezpośredniego nasłonecznienia',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'umiarkowana wilgotność podłoża',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 1,
		name: 'Aglaonema "Brightness Queen"',
		category: 'aglaonema',
		price: 86.0,
		image: './assets/aglaonema_brightness_queen.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'umiarkowana wilgotność podłoża',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 2,
		name: 'Aglaonema "Silverado"',
		category: 'aglaonema',
		price: 57.0,
		image: './assets/aglaonema_silverado.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 3,
		name: 'Aglaonema "Prestige"',
		category: 'aglaonema',
		price: 79.0,
		image: './assets/aglaonema_prestige.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 4,
		name: 'Aglaonema "Crete Flame"',
		category: 'aglaonema',
		price: 60.0,
		image: './assets/aglaonema_crete_flame.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'jako roślina tropikalna źle znosi suszę i lubi zraszanie liści',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podłoże żyzne, próchnicze i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 5,
		name: 'Aglaonema "Cinta"',
		category: 'aglaonema',
		price: 62.0,
		image: './assets/aglaonema_cinta.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'jako roślina tropikalna źle znosi suszę i lubi zraszanie liści',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 6,
		name: 'Aglaonema "Red Lipstick"',
		category: 'aglaonema',
		price: 100.0,
		image: './assets/aglaonema_red_lipstick.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 7,
		name: 'Aglaonema "Chamaeleon Bandit"',
		category: 'aglaonema',
		price: 120.0,
		image: './assets/aglaonema_chamaeleon_bandit.jpg',
		description: [
			'stanowisko półcieniste lub jasne z rozproszonym światłem',
			'potrzebuje dużej ilości światła dla uzyskania ładnego wybarwienia',
			'lubi miejsca ciepłe o temperaturze 20 – 25°C',
			'podlewać obficie, najlepiej miękką wodą',
		],
	},
	{
		id: 8,
		name: 'Ceropegia "Woodii"',
		category: 'ceropegia',
		price: 40.0,
		image: './assets/ceropegia_woodii.jpg',
		description: [
			'stanowisko jasne',
			'brak odpowiedniej ilości światła powoduje, że zwiększa się odległość między liśćmi',
			'lubi miejsca ciepłe o temperaturze 20 – 22°C',
			'podłoże powinno być przepuszczalne i dobrze zdrenowane',
		],
	},
	{
		id: 9,
		name: 'Ceropegia "Woodii Variegata"',
		category: 'ceropegia',
		price: 45.0,
		image: './assets/ceropegia_woodii_variegata.jpg',
		description: [
			'stanowisko jasne',
			'brak odpowiedniej ilości światła powoduje, że zwiększa się odległość między liśćmi',
			'lubi miejsca ciepłe o temperaturze 20 – 22°C',
			'podłoże powinno być przepuszczalne i dobrze zdrenowane',
		],
	},

	{
		id: 10,
		name: 'Ceropegia woodii "Silver Glory"',
		category: 'ceropegia',
		price: 50.0,
		image: './assets/ceropegia_woodii_silver_glory.jpg',
		description: [
			'stanowisko jasne',
			'musi być chroniona przed ostrym, palącym słońcem',
			'nie znosi przeciągów',
			'podłoże powinno być przepuszczalne i dobrze zdrenowane',
		],
	},
	{
		id: 11,
		name: 'Epipremnum "Pearls and Jade"',
		category: 'epipremnum',
		price: 22.0,
		image: './assets/epipremnum_pearls_and_jade.jpg',
		description: [
			'stanowisko jasne',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'nie znosi przeciągów',
			'podłoże żyzne, próchniczne, przepuszczalne',
		],
	},
	{
		id: 12,
		name: 'Epipremnum "Skeleton Key"',
		category: 'epipremnum',
		price: 33.0,
		image: './assets/epipremnum_skeleton_key.jpg',
		description: [
			'stanowisko jasne, ale nie bezpośrednio nasłonecznione',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'unikać zbyt obfitego podlewania',
			'podłoże żyzne, próchniczne, przepuszczalne',
		],
	},
	{
		id: 13,
		name: 'Epipremnum "Jungle Star"',
		category: 'epipremnum',
		price: 42.0,
		image: './assets/epipremnum_aureum_jungle_star_marble_green.jpg',
		description: [
			'toleruje ocienione stanowisko',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'unikać zbyt obfitego podlewania',
			'podłoże powinno zawierać składniki, które zapewnią mu przepuszczalność, takie jak perlit, keramzyt',
		],
	},
	{
		id: 14,
		name: 'Epipremnum aureum',
		category: 'epipremnum',
		price: 19.0,
		image: './assets/epipremnum_aureum.jpg',
		description: [
			'najbardziej odporna odmiana roślin doniczkowych z tego rodzaju',
			'toleruje ocienione stanowisko',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'podłoże żyzne, próchniczne, przepuszczalne',
		],
	},
	{
		id: 15,
		name: 'Epipremnum pinnatum',
		category: 'epipremnum',
		price: 74.0,
		image: './assets/epipremnum_pinnatum_variegata.jpg',
		description: [
			'stanowisko jasne, jednak nie bezpośrednio nasłonecznione',
			'unikać zbyt obfitego podlewania',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'podłoże żyzne, próchniczne, przepuszczalne',
		],
	},
	{
		id: 16,
		name: 'Epipremnum "Global Green"',
		category: 'epipremnum',
		price: 30.0,
		image: './assets/epipremnum_pinnatum_global_green.jpg',
		description: [
			'stanowisko jasne z dużą ilością rozproszonego światła',
			'podłoże powinno nieco wyschnąć przed ponownym podlaniem',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'podłoże żyzne, próchniczne i przepuszczalne o odczynie lekko kwaśnym',
		],
	},
	{
		id: 17,
		name: 'Epipremnum "Happy Leaf"',
		category: 'epipremnum',
		price: 19.0,
		image: './assets/epipremnum_happy_leaf.jpg',
		description: [
			'stanowisko o jasnym, rozproszonym świetle',
			'wymaga podlewania dopiero kiedy ziemia prawie całkowicie przeschnie',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'podłoże żyzne, próchniczne, przepuszczalne',
		],
	},
	{
		id: 18,
		name: 'Monstera deliciosa',
		category: 'monstera',
		price: 30.0,
		image: './assets/monstera_deliciosa.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko o jasnym, rozproszonym świetle',
			'nie toleruje nadmiaru wody',
			'w okresie zimowym warto doświetlać odpowiednimi żarówkami',
		],
	},
	{
		id: 19,
		name: 'Monstera "Pinnatipartita"',
		category: 'monstera',
		price: 69.0,
		image: './assets/monstera_pinnatipartita.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko o jasnym, rozproszonym świetle',
			'nie toleruje nadmiaru wody',
			'ziemia przewiewna, przepuszczalna, torfowa',
		],
	},
	{
		id: 20,
		name: 'Monstera deliciosa "Variegata"',
		category: 'monstera',
		price: 119.0,
		image: './assets/monstera-deliciosa-variegata.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'w okresie zimowym znacznie ograniczamy podlewanie',
			'nie toleruje nadmiaru wody',
			'ziemia przewiewna, przepuszczalna, torfowa',
		],
	},
	{
		id: 21,
		name: 'Monstera acuminata',
		category: 'monstera',
		price: 54.0,
		image: './assets/monstera_acuminata.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'w okresie zimowym znacznie ograniczamy podlewanie',
			'w okresie zimowym warto doświetlać odpowiednimi żarówkami',
			'ziemia przewiewna, przepuszczalna, torfowa',
		],
	},
	{
		id: 22,
		name: 'Monstera"Green on Green"',
		category: 'monstera',
		price: 239.0,
		image: './assets/monstera_green_on_green.jpg',
		description: [
			'stanowisko o jasnym, rozproszonym świetle',
			'wymaga podlewania dopiero kiedy ziemia prawie całkowicie przeschnie',
			'można przycinać, regulując w ten sposób jego wielkość oraz kształt',
			'uwielbia dużą wilgotność powietrza',
		],
	},
	{
		id: 23,
		name: 'Monstera adansonii "Mint"',
		category: 'monstera',
		price: 60.0,
		image: './assets/monstera_adansonii_mint-.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'w okresie zimowym znacznie ograniczamy podlewanie',
			'nie toleruje nadmiaru wody',
			'ziemia przewiewna, przepuszczalna, torfowa',
		],
	},
	{
		id: 24,
		name: 'Philodendron "Pink Princess"',
		category: 'philodendron',
		price: 49.0,
		image: './assets/philodendron_pink_princess.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 25,
		name: 'Philodendron "Lemon Lime"',
		category: 'philodendron',
		price: 45.0,
		image: './assets/philodendron_lemon_lime.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'preferuje dużą wilgotność powietrza',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 26,
		name: 'Philodendron "Imperial Green"',
		category: 'philodendron',
		price: 59.0,
		image: './assets/philodendron_imperial_green.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 27,
		name: 'Philodendron "Silver Queen"',
		category: 'philodendron',
		price: 40.0,
		image: './assets/philodendron_silver_queen.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 28,
		name: 'Philodendron gloriosum',
		category: 'philodendron',
		price: 35.0,
		image: './assets/philodendron_gloriosum.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 29,
		name: 'Philodendron "Fun Bun"',
		category: 'philodendron',
		price: 59.0,
		image: './assets/philodendron_fun_bun.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 30,
		name: 'Philodendron "Florida"',
		category: 'philodendron',
		price: 45.0,
		image: './assets/philodendron_florida.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'stanowisko delikatnie zacienione z pośrednim światłem słonecznym',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 31,
		name: 'Philodendron squamiferum',
		category: 'philodendron',
		price: 42.0,
		image: './assets/philodendron_squamiferum.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 32,
		name: 'Philodendron "Super Atom"',
		category: 'philodendron',
		price: 32.0,
		image: './assets/philodendron_super_atom.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 33,
		name: 'Philodendron "Birkin"',
		category: 'philodendron',
		price: 26.0,
		image: './assets/philodendron_birkin.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 34,
		name: 'Philodendron fibraecataphyllum',
		category: 'philodendron',
		price: 90.0,
		image: './assets/philodendron_fibraecataphyllum.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
	{
		id: 35,
		name: 'Philodendron mayoi',
		category: 'philodendron',
		price: 58.0,
		image: './assets/philodendron_mayoi.jpg',
		description: [
			'roślina niewymagająca i łatwa w uprawie',
			'preferuje dużą wilgotność powietrza',
			'najlepsza temperatura od 18 do 25 stopni',
			'nie toleruje przeciągów',
		],
	},
]
